services:
    backend:
      build: 
        context: ./backend
        dockerfile: Dockerfile
      container_name: og-code-backend
      env_file:
        - ./backend/.env
      ports:
        - "5069:5001"
      environment:
        - NODE_ENV=production
        # MongoDB Atlas connection string
        - MONGO_URI=${MONGO_URI}

      restart: unless-stopped 

    frontend:
      build:
        context: ./frontend
        dockerfile: Dockerfile
      container_name: og-code-frontend
      ports:
        - "8069:5001"
      depends_on:
        - backend
      restart: unless-stopped